version: '3.9'

services:
  postgres:
    # Remove port exposure in production
    environment:
      POSTGRES_INITDB_ARGS: "-c shared_buffers=256MB -c max_connections=200"
    mem_limit: 1g
    cpus: '1'
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    # Remove port exposure in production
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    mem_limit: 768m
    cpus: '0.5'
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  minio:
    # Keep ports for S3 access but restrict if needed
    mem_limit: 1g
    cpus: '1'
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  happy-server:
    environment:
      NODE_ENV: production
    # Remove volume mounts for production
    ports:
      - "3000:3000"
      - "9090:9090"
    mem_limit: 1.5g
    cpus: '1.5'
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "5"
    restart: always

  nginx:
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
